# Copyright 2020-2024 The MathWorks, Inc.

# Workflow that contains jobs to run MATLAB-Proxy unit tests

name: Unit testing of MATLAB Proxy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}